### ISSUE TITLE
File Load issue.

### ISSUE THREAD

**Issue by TheRssFeed** [Torotv/TheTorotv.io#2]
The Files WIll Not Load.
You Need To SHorten The Files!

**Comment by Torotv** [comment]
Oh Okay!
WHo ARe You?

**Comment by TheRssFeed** [comment]
*Today is a change , Be a hero and make a social change!*

*You can make the world a better place*

**Comment by TheRssFeed** [comment]
Oh I'm A Open Source Coder.
I Have A Certificate In Html,CSS,Java,JS,SQL<PHP and Other.
Ih And Thanks for The Pokemon Thingy.

*Today is a change , Be a hero and make a social change!*

*You can make the world a better place*

**Comment by Torotv** [comment]
Ok Thx!
